name: LMS

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-2525}
      POSTGRES_DB: ${DB_NAME:-LMS}
    restart: unless-stopped

volumes:
  postgres_data:
